language: node_js

node_js:
  - '10'

install:
  - npm ci
  - lerna bootstrap --no-ci

script:
  - npm run build
  - npm run test:coverage

after_success: npm run test:send_report



before_deploy:
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
  - lerna run build

deploy:
  provider: script
  script: lerna publish from-package
  email: michal.m.zarach@gmail.com
  skip_cleanup: true
  on:
    repo: michalzaq12/xpda-dev
    branch: master
